### ISSUE TITLE
Dropbox API v1 is now deprecated

### ISSUE THREAD

**Issue by therealkbhat** [chinmaydd/CaaS#2]
Check [this](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) out.

Seeing as how the old endpoints are being phased out, there may be refactoring to be done here. We _do_ have till June 28, 2017; just raising this as a reminder.

**Comment by chinmaydd** [comment]
Good point. The code needed some cleanup anyways :+1:

**Comment by chinmaydd** [comment]
Closing this since #3 solves the issue.
