### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by therealkbhat** [chinmaydd/CaaS#4]
As mentioned in #2, the code can be made a lot cleaner.

Better modularity, argument parsing with `docopt`, and moving config-related lines into a separate file come into mind.

**Comment by ujdcodr** [comment]
Hello fellow WebClub mates, I would like to take up this issue. @therealkbhat which particular files concern you the most?

**Comment by therealkbhat** [comment]
Ah, I think we got most of the refactoring done with the API update.

That said, if you look at the tail end of `client.py`, you can see we're getting commandline arguments in an awkward way. This works here because we'll only have one flag on any one run of the tool, but if you'd like the practice / learning experience, try rewriting that to work with `docopt`.

**Comment by chinmaydd** [comment]
@ujdcodr Apart from what @therealkbhat mentioned, you could also look to improve upon the tool. If you read the source closely, we have mentioned some "TODOS" in the file. Try working on those. 

The code is well... dirty. Its a scratch implementation. It would be interesting to see what design changes you can make to make it look/perform better. For "good" python code, you could look at any Airbnb repo. They are usually well written.

**Comment by ujdcodr** [comment]
I'll try my best

**Comment by ujdcodr** [comment]
db = pickledb.load('storage.db', 'False')
What does the 'False' placeholder indicate?

**Comment by therealkbhat** [comment]
It's not a placeholder.

If you set it to `True`, you can use `db.dump()` to write the database from memory to the file specified in `load`.

Reference: <https://pythonhosted.org/pickleDB/commands.html>

**Comment by chinmaydd** [comment]
#5 solves this issue. Although the entire project could love some refactoring in terms of making it generic and usable with any particular CSP API, I think we can close this for now. @therealkbhat thoughts?

**Comment by therealkbhat** [comment]
@chinmaydd sounds good to me.
